# Generated by Django 2.1.2 on 2018-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_author', models.CharField(max_length=250)),
                ('article_title', models.CharField(max_length=250)),
                ('article_body', models.TextField()),
                ('article_category', models.CharField(choices=[('P', 'Politics'), ('E', 'Entertainment')], max_length=1)),
                ('article_slug', models.SlugField(blank=True, max_length=300)),
                ('article_image', models.ImageField(upload_to='article_image')),
                ('article_creation', models.DateTimeField(auto_now_add=True)),
                ('article_update', models.DateTimeField(auto_now=True)),
                ('article_created_at', models.DateTimeField(auto_now_add=True)),
                ('article_updated_at', models.DateTimeField(auto_now=True)),
                ('article_views', models.PositiveIntegerField()),
            ],
        ),
    ]
