# Generated by Django 2.1.2 on 2018-11-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
    ]
